import type { GeneratedGuide } from "@/lib/types";

/**
 * Plain-text checklist of every step and command, for printing or pasting
 * into notes. Pure function: no DOM, no side effects.
 */
export function generateChecklistText(
  stackName: string,
  guide: GeneratedGuide,
): string {
  const lines: string[] = [
    `${stackName} install checklist`,
    "Generated by Agent Deploy",
    "",
  ];

  guide.steps.forEach((step, index) => {
    lines.push(`[ ] ${index + 1}. ${step.title}`);
    lines.push(`    ${step.description}`);
    if (step.note) {
      lines.push(`    Note: ${step.note}`);
    }
    for (const command of step.commands) {
      for (const commandLine of command.split("\n")) {
        lines.push(`    $ ${commandLine}`);
      }
    }
    lines.push("");
  });

  if (guide.verificationChecks.length > 0) {
    lines.push("Verification");
    for (const check of guide.verificationChecks) {
      lines.push(`[ ] ${check.label}`);
      lines.push(`    $ ${check.command}`);
      if (check.expectedOutput) {
        lines.push(`    Expected: ${check.expectedOutput}`);
      }
    }
    lines.push("");
  }

  return lines.join("\n");
}
