import type {
  AgentStack,
  GeneratedGuide,
  InstallStep,
  Model,
  ServerDetails,
  StackOption,
  TroubleshootingItem,
  VerificationCheck,
} from "@/lib/types";
import { computeFitCheck } from "./fit";
import {
  buildTemplateContext,
  renderArray,
  renderTemplate,
  type TemplateContext,
} from "./template";

export interface GenerateGuideInput {
  stack: AgentStack;
  selectedModels: Model[];
  selectedOptions: StackOption[];
  server: ServerDetails;
}

function buildContext(
  selectedModels: Model[],
  server: ServerDetails,
): TemplateContext {
  return buildTemplateContext(server, selectedModels);
}

function expandModelCommands(
  commands: string[],
  context: TemplateContext,
): string[] {
  const expanded: string[] = [];
  for (const command of commands) {
    if (command.includes("{{model_ollama_name}}")) {
      for (const model of context.models) {
        expanded.push(
          command.replace(/\{\{model_ollama_name\}\}/g, model.ollamaName),
        );
      }
    } else {
      expanded.push(command);
    }
  }
  return expanded;
}

function renderStep(step: InstallStep, context: TemplateContext): InstallStep {
  return {
    title: renderTemplate(step.title, context),
    description: renderTemplate(step.description, context),
    commands: renderArray(
      expandModelCommands(step.commands, context),
      context,
    ),
    note: step.note ? renderTemplate(step.note, context) : undefined,
  };
}

function renderVerificationCheck(
  check: VerificationCheck,
  context: TemplateContext,
): VerificationCheck {
  return {
    id: check.id,
    label: renderTemplate(check.label, context),
    command: renderArray([check.command], context).join("\n"),
    expectedOutput: check.expectedOutput
      ? renderTemplate(check.expectedOutput, context)
      : undefined,
  };
}

function renderTroubleshootingItem(
  item: TroubleshootingItem,
  context: TemplateContext,
): TroubleshootingItem {
  return {
    id: item.id,
    problem: renderTemplate(item.problem, context),
    solution: renderTemplate(item.solution, context),
    commands: item.commands
      ? renderArray(expandModelCommands(item.commands, context), context)
      : undefined,
  };
}

function generateScript(
  stack: AgentStack,
  steps: InstallStep[],
  context: TemplateContext,
): string {
  const isWindows = context.family === "windows";

  // `#` is a comment in both bash and PowerShell, so the Agent Deploy marker
  // required by the Gist endpoint is valid in either dialect.
  const lines: string[] = isWindows
    ? [
        "#Requires -RunAsAdministrator",
        "$ErrorActionPreference = 'Stop'",
        "",
        "# Generated by Agent Deploy",
        `# ${stack.name} installer (PowerShell)`,
        `# Generated for ${context.server.ip || "YOUR_SERVER_IP"}`,
        "",
        `Write-Host "Starting installation of ${stack.name}..."`,
        "",
      ]
    : [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by Agent Deploy",
        `# ${stack.name} installer`,
        `# Generated for ${context.server.ip || "YOUR_SERVER_IP"}`,
        "",
        `echo "Starting installation of ${stack.name}..."`,
        "",
      ];

  for (const step of steps) {
    lines.push(`# ${step.title}`);
    lines.push(`# ${step.description}`);
    if (step.note) {
      lines.push(`# Note: ${step.note}`);
    }
    for (const command of step.commands) {
      lines.push(command);
    }
    lines.push("");
  }

  lines.push(
    isWindows
      ? 'Write-Host "Installation complete. Run verification checks from the guide."'
      : 'echo "Installation complete. Run verification checks from the guide."',
  );

  return lines.join("\n");
}

function generateOneLineCommand(script: string, context: TemplateContext): string {
  if (context.family === "windows") {
    const marker = "@'";
    return [
      `$script = ${marker}`,
      script.replace(/'@/g, "' @"),
      "'@",
      "$path = Join-Path $env:TEMP 'agent-deploy-install.ps1'",
      "Set-Content -Path $path -Value $script -Encoding UTF8",
      "powershell -ExecutionPolicy Bypass -File $path",
    ].join("\n");
  }

  const marker = "AGENT_DEPLOY_INSTALL";
  const escapedScript = script.replace(/\\/g, "\\\\").replace(/'/g, "'\\''");
  return [
    `cat <<'${marker}' > /tmp/agent-deploy-install.sh`,
    escapedScript,
    marker,
    "bash /tmp/agent-deploy-install.sh",
  ].join("\n");
}

export function generateGuide(input: GenerateGuideInput): GeneratedGuide {
  const context = buildContext(input.selectedModels, input.server);

  const steps = input.stack.installSteps.map((step) => renderStep(step, context));
  const verificationChecks = input.stack.verificationChecks.map((check) =>
    renderVerificationCheck(check, context),
  );
  const troubleshooting = input.stack.troubleshooting.map((item) =>
    renderTroubleshootingItem(item, context),
  );

  const script = generateScript(input.stack, steps, context);
  const oneLineCommand = generateOneLineCommand(script, context);
  const fitCheck = computeFitCheck(
    input.stack,
    input.selectedModels,
    input.selectedOptions,
    input.server,
  );

  const translate = (commands: string[]): string[] =>
    renderArray(commands, context);

  return {
    script,
    oneLineCommand,
    steps,
    verificationChecks,
    troubleshooting,
    recoveryCommands: translate(input.stack.recoveryCommands ?? []),
    supportInfoCommands: translate(input.stack.supportInfoCommands ?? []),
    fitCheck,
    osFamily: context.family,
    scriptFilename: `${input.stack.id}-install.${context.family === "windows" ? "ps1" : "sh"}`,
    osSupported: input.stack.requirements.os.includes(input.server.operatingSystem),
  };
}
