import { useState } from "react";
import { openInCodePen } from "@/lib/share/codepen";

interface ShareActionsProps {
  stackName: string;
  script: string;
  onDownload: () => void;
}

export function ShareActions({ stackName, script, onDownload }: ShareActionsProps) {
  const [penBlocked, setPenBlocked] = useState(false);

  return (
    <div className="space-y-3">
      <div className="flex flex-wrap gap-3">
        <button
          type="button"
          onClick={onDownload}
          className="inline-flex items-center gap-2 rounded-xl bg-accent px-4 py-2.5 text-sm font-medium text-text-inverse hover:bg-accent-hover transition-colors"
        >
          <i className="fa-solid fa-download" />
          Download script
        </button>

        <button
          type="button"
          onClick={() => {
            const opened = openInCodePen({
              title: `${stackName} install script`,
              description: "Generated by Agent Deploy",
              script,
            });
            setPenBlocked(!opened);
          }}
          className="inline-flex items-center gap-2 rounded-xl border border-border bg-surface px-4 py-2.5 text-sm font-medium text-text hover:bg-surface-muted transition-colors"
        >
          <i className="fa-brands fa-codepen" />
          Save to CodePen
        </button>
      </div>

      {penBlocked && (
        <p className="rounded-xl border border-warning/30 bg-warning-subtle/30 px-4 py-3 text-sm text-warning">
          Your browser blocked the new tab for CodePen. Allow pop-ups for this
          page, or open the app in its own tab, then try again.
        </p>
      )}

      <p className="text-xs text-text-muted">
        The script contains the server address you entered. Review it before
        sharing it with anyone.
      </p>
    </div>
  );
}
