import { useRef, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { createGist, getCaptchaSiteKey } from "@/lib/share/gist.functions";
import { openInCodePen } from "@/lib/share/codepen";
import {
  HCaptcha,
  type HCaptchaHandle,
} from "@/design-system/font-awsome-web-awesome-171158/webawesome/patterns/hcaptcha";

interface ShareActionsProps {
  stackId: string;
  stackName: string;
  script: string;
  onDownload: () => void;
}

export function ShareActions({
  stackId,
  stackName,
  script,
  onDownload,
}: ShareActionsProps) {
  const saveGist = useServerFn(createGist);
  const loadSiteKey = useServerFn(getCaptchaSiteKey);
  const captchaRef = useRef<HCaptchaHandle>(null);
  const [copied, setCopied] = useState(false);
  const [penBlocked, setPenBlocked] = useState(false);
  const [verifying, setVerifying] = useState(false);

  const siteKeyQuery = useQuery({
    queryKey: ["captcha-site-key"],
    queryFn: () => loadSiteKey({}),
    enabled: verifying,
    staleTime: Infinity,
  });

  const gistMutation = useMutation({
    mutationFn: (captchaToken: string) =>
      saveGist({
        data: {
          filename: `${stackId}-install.sh`,
          content: script,
          description: `${stackName} install script — generated by Agent Deploy`,
          captchaToken,
        },
      }),
    onSettled: () => {
      captchaRef.current?.reset();
      setVerifying(false);
    },
  });

  const copyLink = async (url: string) => {
    await navigator.clipboard.writeText(url);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 2000);
  };

  const siteKey = siteKeyQuery.data?.siteKey ?? null;

  return (
    <div className="space-y-3">
      <div className="flex flex-wrap gap-3">
        <button
          type="button"
          onClick={onDownload}
          className="inline-flex items-center gap-2 rounded-xl bg-accent px-4 py-2.5 text-sm font-medium text-text-inverse hover:bg-accent-hover transition-colors"
        >
          <i className="fa-solid fa-download" />
          Download script
        </button>

        <button
          type="button"
          onClick={() => {
            const opened = openInCodePen({
              title: `${stackName} install script`,
              description: "Generated by Agent Deploy",
              script,
            });
            setPenBlocked(!opened);
          }}
          className="inline-flex items-center gap-2 rounded-xl border border-border bg-surface px-4 py-2.5 text-sm font-medium text-text hover:bg-surface-muted transition-colors"
        >
          <i className="fa-brands fa-codepen" />
          Save to CodePen
        </button>

        <button
          type="button"
          onClick={() => setVerifying(true)}
          disabled={gistMutation.isPending || verifying}
          className="inline-flex items-center gap-2 rounded-xl border border-border bg-surface px-4 py-2.5 text-sm font-medium text-text hover:bg-surface-muted transition-colors disabled:opacity-60"
        >
          <i
            className={
              gistMutation.isPending
                ? "fa-solid fa-spinner fa-spin"
                : "fa-brands fa-github"
            }
          />
          {gistMutation.isPending ? "Saving…" : "Save to Gist"}
        </button>
      </div>

      {verifying && (
        <div className="space-y-2 rounded-xl border border-border bg-surface-muted px-4 py-3">
          <p className="text-sm text-text">
            Quick check to confirm you're not a bot, then the Gist is created.
          </p>
          {siteKey ? (
            <HCaptcha
              ref={captchaRef}
              siteKey={siteKey}
              onVerify={(token) => gistMutation.mutate(token)}
            />
          ) : siteKeyQuery.isError || siteKeyQuery.isSuccess ? (
            <p className="text-sm text-warning">
              Saving to Gist is unavailable right now. You can still download the
              script or save it to CodePen.
            </p>
          ) : (
            <p className="text-sm text-text-muted">Loading the check…</p>
          )}
        </div>
      )}

      {gistMutation.isSuccess && (
        <div className="flex flex-wrap items-center gap-3 rounded-xl border border-border bg-surface-muted px-4 py-3 text-sm">
          <a
            href={gistMutation.data.url}
            target="_blank"
            rel="noreferrer noopener"
            className="font-medium text-accent hover:underline break-all"
          >
            {gistMutation.data.url}
          </a>
          <button
            type="button"
            onClick={() => void copyLink(gistMutation.data.url)}
            className="inline-flex items-center gap-2 rounded-lg border border-border bg-surface px-3 py-1.5 text-xs font-medium text-text hover:bg-surface-muted transition-colors"
          >
            <i className={copied ? "fa-solid fa-check" : "fa-solid fa-copy"} />
            {copied ? "Copied" : "Copy link"}
          </button>
        </div>
      )}

      {penBlocked && (
        <p className="rounded-xl border border-warning/30 bg-warning-subtle/30 px-4 py-3 text-sm text-warning">
          Your browser blocked the new tab for CodePen. Allow pop-ups for this
          page, or open the app in its own tab, then try again.
        </p>
      )}

      {gistMutation.isError && (
        <p className="rounded-xl border border-warning/30 bg-warning-subtle/30 px-4 py-3 text-sm text-warning">
          {gistMutation.error instanceof Error
            ? gistMutation.error.message
            : "Could not save the Gist."}
        </p>
      )}

      <p className="text-xs text-text-muted">
        Saved links are unlisted, but anyone with the link can read them. The
        script contains the server address you entered.
      </p>
    </div>
  );
}
