import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { createGist } from "@/lib/share/gist.functions";
import { openInCodePen } from "@/lib/share/codepen";

interface ShareActionsProps {
  stackId: string;
  stackName: string;
  script: string;
  onDownload: () => void;
}

export function ShareActions({
  stackId,
  stackName,
  script,
  onDownload,
}: ShareActionsProps) {
  const saveGist = useServerFn(createGist);
  const [copied, setCopied] = useState(false);

  const gistMutation = useMutation({
    mutationFn: () =>
      saveGist({
        data: {
          filename: `${stackId}-install.sh`,
          content: script,
          description: `${stackName} install script — generated by Agent Deploy`,
        },
      }),
  });

  const copyLink = async (url: string) => {
    await navigator.clipboard.writeText(url);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-3">
      <div className="flex flex-wrap gap-3">
        <button
          type="button"
          onClick={onDownload}
          className="inline-flex items-center gap-2 rounded-xl bg-accent px-4 py-2.5 text-sm font-medium text-text-inverse hover:bg-accent-hover transition-colors"
        >
          <i className="fa-solid fa-download" />
          Download script
        </button>

        <button
          type="button"
          onClick={() =>
            openInCodePen({
              title: `${stackName} install script`,
              description: "Generated by Agent Deploy",
              script,
            })
          }
          className="inline-flex items-center gap-2 rounded-xl border border-border bg-surface px-4 py-2.5 text-sm font-medium text-text hover:bg-surface-muted transition-colors"
        >
          <i className="fa-brands fa-codepen" />
          Save to CodePen
        </button>

        <button
          type="button"
          onClick={() => gistMutation.mutate()}
          disabled={gistMutation.isPending}
          className="inline-flex items-center gap-2 rounded-xl border border-border bg-surface px-4 py-2.5 text-sm font-medium text-text hover:bg-surface-muted transition-colors disabled:opacity-60"
        >
          <i
            className={
              gistMutation.isPending
                ? "fa-solid fa-spinner fa-spin"
                : "fa-brands fa-github"
            }
          />
          {gistMutation.isPending ? "Saving…" : "Save to Gist"}
        </button>
      </div>

      {gistMutation.isSuccess && (
        <div className="flex flex-wrap items-center gap-3 rounded-xl border border-border bg-surface-muted px-4 py-3 text-sm">
          <a
            href={gistMutation.data.url}
            target="_blank"
            rel="noreferrer noopener"
            className="font-medium text-accent hover:underline break-all"
          >
            {gistMutation.data.url}
          </a>
          <button
            type="button"
            onClick={() => void copyLink(gistMutation.data.url)}
            className="inline-flex items-center gap-2 rounded-lg border border-border bg-surface px-3 py-1.5 text-xs font-medium text-text hover:bg-surface-muted transition-colors"
          >
            <i className={copied ? "fa-solid fa-check" : "fa-solid fa-copy"} />
            {copied ? "Copied" : "Copy link"}
          </button>
        </div>
      )}

      {gistMutation.isError && (
        <p className="rounded-xl border border-warning/30 bg-warning-subtle/30 px-4 py-3 text-sm text-warning">
          {gistMutation.error instanceof Error
            ? gistMutation.error.message
            : "Could not save the Gist."}
        </p>
      )}

      <p className="text-xs text-text-muted">
        Saved links are unlisted, but anyone with the link can read them. The
        script contains the server address you entered.
      </p>
    </div>
  );
}
