import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";

const GATEWAY_URL = "https://connector-gateway.lovable.dev/github";
const HCAPTCHA_VERIFY_URL = "https://api.hcaptcha.com/siteverify";

/** Only install scripts generated by this app may be published. */
const SCRIPT_MARKER = "Agent Deploy";

const createGistInput = z.object({
  filename: z
    .string()
    .max(100)
    .regex(/^[\w.-]+\.sh$/, "Filename must be a simple .sh name"),
  content: z
    .string()
    .min(1)
    .max(40_000)
    .refine(
      (value) => value.startsWith("#!/") && value.includes(SCRIPT_MARKER),
      "Only install scripts generated by this app can be saved.",
    ),
  description: z.string().max(200),
  captchaToken: z.string().min(1).max(10_000),
});

export type CreateGistInput = z.infer<typeof createGistInput>;

export interface CreateGistResult {
  url: string;
}

const WINDOW_SECONDS = 60 * 60;
const MAX_PER_WINDOW = 5;
const MAX_GLOBAL_PER_WINDOW = 60;

async function clientKey(): Promise<string> {
  try {
    const { getRequest } = await import("@tanstack/start-server-core");
    const headers = getRequest().headers;
    const forwarded = headers.get("x-forwarded-for");
    const ip =
      headers.get("cf-connecting-ip") ??
      (forwarded ? forwarded.split(",")[0]?.trim() : null) ??
      headers.get("x-real-ip");
    return ip && ip.length > 0 ? `ip:${ip}` : "ip:unknown";
  } catch {
    return "ip:unknown";
  }
}

/** Publishable hCaptcha site key, safe to hand to the browser. */
export const getCaptchaSiteKey = createServerFn({ method: "GET" }).handler(
  async (): Promise<{ siteKey: string | null }> => ({
    siteKey: process.env["HCAPTCHA_SITE_KEY"] ?? null,
  }),
);

async function verifyCaptcha(token: string, remoteIp: string | null) {
  const secret = process.env["HCAPTCHA_SECRET_KEY"];
  if (!secret) {
    throw new Error("Verification is not configured for this app.");
  }

  const body = new URLSearchParams({ secret, response: token });
  if (remoteIp) body.set("remoteip", remoteIp);

  const response = await fetch(HCAPTCHA_VERIFY_URL, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body,
  });

  if (!response.ok) {
    console.error(`hCaptcha verification failed [${response.status}]`);
    throw new Error("Could not check the verification challenge. Try again.");
  }

  const result = (await response.json()) as { success?: boolean };
  if (!result.success) {
    throw new Error("Verification failed. Please try the challenge again.");
  }
}

export const createGist = createServerFn({ method: "POST" })
  .inputValidator((data: unknown) => createGistInput.parse(data))
  .handler(async ({ data }): Promise<CreateGistResult> => {
    const key = await clientKey();
    const ip = key.startsWith("ip:") && key !== "ip:unknown" ? key.slice(3) : null;

    await verifyCaptcha(data.captchaToken, ip);

    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");

    const global = await supabaseAdmin.rpc("consume_rate_limit", {
      _key: "gist:global",
      _limit: MAX_GLOBAL_PER_WINDOW,
      _window_seconds: WINDOW_SECONDS,
    });
    if (global.error) {
      console.error(`Rate limit check failed: ${global.error.message}`);
      throw new Error("Could not save the Gist right now. Please try again later.");
    }
    if (global.data === false) {
      throw new Error("Saving to Gist is busy right now. Please try again later.");
    }

    const perClient = await supabaseAdmin.rpc("consume_rate_limit", {
      _key: `gist:${key}`,
      _limit: MAX_PER_WINDOW,
      _window_seconds: WINDOW_SECONDS,
    });
    if (perClient.error) {
      console.error(`Rate limit check failed: ${perClient.error.message}`);
      throw new Error("Could not save the Gist right now. Please try again later.");
    }
    if (perClient.data === false) {
      throw new Error(
        "You've saved several scripts recently. Please wait a while before saving another.",
      );
    }

    const lovableApiKey = process.env["LOVABLE_API_KEY"];
    const githubApiKey = process.env["GITHUB_API_KEY"];
    if (!lovableApiKey || !githubApiKey) {
      throw new Error("GitHub is not connected for this app.");
    }

    const response = await fetch(`${GATEWAY_URL}/gists`, {
      method: "POST",
      headers: {
        Accept: "application/vnd.github+json",
        "Content-Type": "application/json",
        Authorization: `Bearer ${lovableApiKey}`,
        "X-Connection-Api-Key": githubApiKey,
      },
      body: JSON.stringify({
        description: data.description,
        public: false,
        files: { [data.filename]: { content: data.content } },
      }),
    });

    if (!response.ok) {
      const errorBody = await response.text();
      console.error(`Gist creation failed [${response.status}]: ${errorBody}`);
      throw new Error(`Could not save the Gist [${response.status}]`);
    }

    const body = (await response.json()) as { html_url?: string };
    if (!body.html_url) {
      throw new Error("GitHub did not return a Gist link.");
    }

    return { url: body.html_url };
  });
