import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";

const GATEWAY_URL = "https://connector-gateway.lovable.dev/github";

/** Only install scripts generated by this app may be published. */
const SCRIPT_MARKER = "Agent Deploy";

const createGistInput = z.object({
  filename: z
    .string()
    .max(100)
    .regex(/^[\w.-]+\.sh$/, "Filename must be a simple .sh name"),
  content: z
    .string()
    .min(1)
    .max(40_000)
    .refine(
      (value) => value.startsWith("#!/") && value.includes(SCRIPT_MARKER),
      "Only install scripts generated by this app can be saved.",
    ),
  description: z.string().max(200),
});

export type CreateGistInput = z.infer<typeof createGistInput>;

export interface CreateGistResult {
  url: string;
}

const WINDOW_MS = 60 * 60 * 1000;
const MAX_PER_WINDOW = 5;
const MAX_GLOBAL_PER_WINDOW = 60;

interface Bucket {
  count: number;
  resetAt: number;
}

const buckets = new Map<string, Bucket>();

function takeToken(key: string, limit: number, now: number): boolean {
  const bucket = buckets.get(key);
  if (!bucket || bucket.resetAt <= now) {
    buckets.set(key, { count: 1, resetAt: now + WINDOW_MS });
    return true;
  }
  if (bucket.count >= limit) return false;
  bucket.count += 1;
  return true;
}

function pruneBuckets(now: number): void {
  for (const [key, bucket] of buckets) {
    if (bucket.resetAt <= now) buckets.delete(key);
  }
}

function clientKey(): string {
  try {
    const headers = getRequest().headers;
    const forwarded = headers.get("x-forwarded-for");
    const ip =
      headers.get("cf-connecting-ip") ??
      (forwarded ? forwarded.split(",")[0]?.trim() : null) ??
      headers.get("x-real-ip");
    return ip && ip.length > 0 ? `ip:${ip}` : "ip:unknown";
  } catch {
    return "ip:unknown";
  }
}

export const createGist = createServerFn({ method: "POST" })
  .inputValidator((data: unknown) => createGistInput.parse(data))
  .handler(async ({ data }): Promise<CreateGistResult> => {
    const now = Date.now();
    pruneBuckets(now);

    if (!takeToken("global", MAX_GLOBAL_PER_WINDOW, now)) {
      throw new Error("Saving to Gist is busy right now. Please try again later.");
    }
    if (!takeToken(clientKey(), MAX_PER_WINDOW, now)) {
      throw new Error(
        "You've saved several scripts recently. Please wait a while before saving another.",
      );
    }

    const lovableApiKey = process.env["LOVABLE_API_KEY"];
    const githubApiKey = process.env["GITHUB_API_KEY"];
    if (!lovableApiKey || !githubApiKey) {
      throw new Error("GitHub is not connected for this app.");
    }

    const response = await fetch(`${GATEWAY_URL}/gists`, {
      method: "POST",
      headers: {
        Accept: "application/vnd.github+json",
        "Content-Type": "application/json",
        Authorization: `Bearer ${lovableApiKey}`,
        "X-Connection-Api-Key": githubApiKey,
      },
      body: JSON.stringify({
        description: data.description,
        public: false,
        files: { [data.filename]: { content: data.content } },
      }),
    });

    if (!response.ok) {
      const errorBody = await response.text();
      console.error(`Gist creation failed [${response.status}]: ${errorBody}`);
      throw new Error(`Could not save the Gist [${response.status}]`);
    }

    const body = (await response.json()) as { html_url?: string };
    if (!body.html_url) {
      throw new Error("GitHub did not return a Gist link.");
    }

    return { url: body.html_url };
  });
